### ISSUE TITLE
Localizing functions for speedup

### ISSUE THREAD

**Issue by adriweb** [TheLocust3/Ti-Nspire-Gameboy-Classic-Emulator#1]
I've noticed the frequent use of unlocalized functions like `math.floor`, `string.sub` etc. While this is OK for most scripts, we really want to be as fast as possible here, so, prefer using localized versions instead (declared at the top of the script, for instance), as recommended by the [Lua Performance Tips .pdf](http://www.lua.org/gems/sample.pdf):
```lua
local stringsub = string.sub
local mathfloor = math.floor
...
```

Also, I've created [this presentation](https://tiplanet.org/forum/archives_voir.php?id=280698), about advanced lua tips, maybe some of the things can be helpful :)

*BTW, I've talked about this project to @jimbauwens, a fellow TI-Nspire Lua programmer, who has created many apps and cool stuff, including an fast bitop lib, so he may help you out speeding up yours :)*

**Comment by TheLocust3** [comment]
Sorry for taking so long to respond to this issue. I have just implemented the change that you suggested. Thanks for the tip.
