### ISSUE TITLE
Class usage

### ISSUE THREAD

**Issue by adriweb** [TheLocust3/Ti-Nspire-Gameboy-Classic-Emulator#10]
I noticed you've redefined `class`, why not use the one TI embedded?

You can find an example here: https://wiki.inspired-lua.org/Balls_Example
(TI implemented it like that: https://wiki.inspired-lua.org/class )

**Comment by TheLocust3** [comment]
I am looking at this, but I don't see any mention of inheritance. Do you know if that feature is supported?

**Comment by adriweb** [comment]
You can specify the parent class as the parameter of class() actually.

**Comment by TheLocust3** [comment]
Awesome, I will be implementing this. It doesn't seem like a very large change anyways.

**Comment by adriweb** [comment]
Nope it should be mostly the same. I think the only difference is that TI's doesn't call the parent constructor automatically, from what I've seen in the other code.
See my example above, anyway.
