### ISSUE TITLE
Fix ternary assignments

### ISSUE THREAD

**Issue by adriweb** [TheLocust3/Ti-Nspire-Gameboy-Classic-Emulator#2]
Not sure if you had seen my commit comment at the time, but there you go: https://github.com/TheLocust3/Ti-Nspire-Gameboy-Classic-Emulator/commit/cfc379c7326765a09cace88b3e1fc672dfea0754#commitcomment-12336201

>> `lcdDisplay = bValue[8] == 0 and false or true`

> This doesn't work the way you want to - it will always be true. See http://lua-users.org/wiki/TernaryOperator
> Fix: since you just want a boolean, don't use ternaries. Invert the condition when you want false.
> Here, the line becomes: `lcdDisplay = bValue[8] ~= 0`
> Same for the other `and false or true` expressions you use below.
> Regarding the `and true or false` ones, you can simply drop those ternary, since it's already a boolean that's returned in the test.

**Comment by TheLocust3** [comment]
I have just fixed it. I am closing this issue for now, but I have a question. Are the other ternary assignments (for instance `bValue[5] == 0 and {0x8800, 0x97ff} or {0x8000, 0x8fff}`) affected by this issue?

**Comment by adriweb** [comment]
As long as the value for the true condition is not `false` nor `nil`, it should be good. So, tables are OK.

**Comment by TheLocust3** [comment]
Alright, thanks.
